### ISSUE TITLE
signin error if Callback URL is not set on Twitter in the application settings

### ISSUE THREAD

**Issue by Zarandor** [TomGrill/gdx-twitter#4]
I encountered the same issue as decribed here:
http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=21268&p=88085&hilit=gdx+twitter#p88085

So I put a url in the application settings even though I have no use of it and sign in was then successful.

**Comment by TomGrill** [comment]
I added this to the readme. Thanks
