### ISSUE TITLE
java.lang.RuntimeException: No libGDX environment. 

### ISSUE THREAD

**Issue by Zarandor** [TomGrill/gdx-twitter#7]
Hi,
my application crashes at launch and here are the 2 relevant lines in the logcat that point out the issue:
java.lang.RuntimeException: No libGDX environment. 
	at bvm.<init>(TwitterSystem.java:1057)

It happens when proguard is enable.
Can you indicate me which proguard instructions I have to specify to make it work ?

**Comment by Zarandor** [comment]
After some digging here's what I set to make it work:

-keep class com.badlogic.gdx.Gdx { *; }
-keep class com.badlogic.gdx.Application { *; }
-keep class com.badlogic.gdx.LifecycleListener { *; }
-keep class de.tomgrill.gdxtwitter.** { *; }

**Comment by TomGrill** [comment]
Thanks, I will add to the readme.
